export const GET_CASES = "GET_CASES";
export const GET_CASES_SUCCESS = "GET_CASES_SUCCESS";
export const GET_CASES_FAIL = "GET_CASES_FAIL";

export const GET_CASE = "GET_CASE";
export const GET_CASE_SUCCESS = "GET_CASE_SUCCESS";
export const GET_CASE_FAIL = "GET_CASE_FAIL";

export const CREATE_CASE = "CREATE_CASE";
export const CREATE_CASE_SUCCESS = "CREATE_CASE_SUCCESS";
export const CREATE_CASE_FAIL = "CREATE_CASE_FAIL";

export const UPDATE_CASE = "UPDATE_CASE";
export const UPDATE_CASE_SUCCESS = "UPDATE_CASE_SUCCESS";
export const UPDATE_CASE_FAIL = "UPDATE_CASE_FAIL";

export const DELETE_CASE = "DELETE_CASE";
export const DELETE_CASE_SUCCESS = "DELETE_CASE_SUCCESS";
export const DELETE_CASE_FAIL = "DELETE_CASE_FAIL";

export const RESET_STATE = "RESET_STATE";

export const RESET_STATUS = "RESET_STATUS";
